import type { ClassEntry, ClassType } from './types';

const OFFICIAL_TYPES: ClassType[] = ['CLASS_PHYSICAL', 'CLASS_VLE', 'PRACTICAL'];

export const DEFAULT_CLASSES: Omit<ClassEntry, 'createdAt' | 'updatedAt'>[] = [
  { id: 'mon-1', courseCode: 'REST', courseName: 'Morning Rest', day: 'Monday', startTime: '07:00', endTime: '09:00', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: '', isDefault: true },
  { id: 'mon-2', courseCode: 'MN 372', courseName: 'Underground Mining Systems', day: 'Monday', startTime: '11:00', endTime: '12:00', venue: 'VLE', lecturer: 'BT AKUNOR', type: 'CLASS_VLE', notificationEnabled: true, notificationMinsBefore: 10, notes: '', isDefault: true },
  { id: 'mon-3', courseCode: 'MN 372', courseName: 'Underground Mining Systems', day: 'Monday', startTime: '12:00', endTime: '13:00', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Review lecture notes.', isDefault: true },
  { id: 'mon-4', courseCode: 'MN 376', courseName: 'Surface Mine Planning & Design', day: 'Monday', startTime: '13:00', endTime: '14:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Prep for Tuesday MN376.', isDefault: true },
  { id: 'mon-5', courseCode: 'MN 350', courseName: 'Mineral Resource Estimation', day: 'Monday', startTime: '14:30', endTime: '15:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Prep for Tuesday field work.', isDefault: true },
  { id: 'mon-6', courseCode: 'MN 374', courseName: 'Surface Mining Systems', day: 'Monday', startTime: '15:30', endTime: '16:30', venue: 'CCG2', lecturer: 'AB YALEY', type: 'CLASS_PHYSICAL', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Priority 3-credit course.', isDefault: true },
  { id: 'mon-7', courseCode: 'MN 374', courseName: 'Surface Mining Systems', day: 'Monday', startTime: '16:30', endTime: '18:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: "Consolidate today's class.", isDefault: true },
  { id: 'mon-8', courseCode: 'REST', courseName: 'Wind Down', day: 'Monday', startTime: '18:30', endTime: '19:30', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: '', isDefault: true },

  { id: 'tue-1', courseCode: 'REST', courseName: 'Morning Rest', day: 'Tuesday', startTime: '07:00', endTime: '09:00', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: '', isDefault: true },
  { id: 'tue-2', courseCode: 'MN 376', courseName: 'Surface Mine Planning & Design', day: 'Tuesday', startTime: '09:00', endTime: '11:00', venue: '', lecturer: 'JB BAIDOE', type: 'CLASS_PHYSICAL', notificationEnabled: true, notificationMinsBefore: 10, notes: '2 hour class.', isDefault: true },
  { id: 'tue-3', courseCode: 'MN 372', courseName: 'Underground Mining Systems', day: 'Tuesday', startTime: '11:00', endTime: '12:00', venue: '', lecturer: 'BT AKUNOR', type: 'PRACTICAL', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Practical session.', isDefault: true },
  { id: 'tue-4', courseCode: 'MN 374', courseName: 'Surface Mining Systems', day: 'Tuesday', startTime: '12:00', endTime: '13:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Prep for Wednesday MN374.', isDefault: true },
  { id: 'tue-5', courseCode: 'MN 350', courseName: 'Mineral Resource Estimation', day: 'Tuesday', startTime: '13:30', endTime: '15:30', venue: 'GR 1', lecturer: 'CK ARTHUR', type: 'PRACTICAL', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Field Work 2. 2 hours.', isDefault: true },
  { id: 'tue-6', courseCode: 'REST', courseName: 'Break after fieldwork', day: 'Tuesday', startTime: '15:30', endTime: '16:30', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: '', isDefault: true },
  { id: 'tue-7', courseCode: 'MN 380', courseName: 'Mine Drainage', day: 'Tuesday', startTime: '16:30', endTime: '17:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Prep for Wednesday MN380(P).', isDefault: true },
  { id: 'tue-8', courseCode: 'MN 352', courseName: 'Research Methods & Ethics', day: 'Tuesday', startTime: '17:30', endTime: '18:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Prep for Wednesday MN352.', isDefault: true },
  { id: 'tue-9', courseCode: 'MN 370', courseName: 'Computer Applications in Mining', day: 'Tuesday', startTime: '18:30', endTime: '19:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Prep for Wednesday MN370(P).', isDefault: true },
  { id: 'tue-10', courseCode: 'REST', courseName: 'Wind Down', day: 'Tuesday', startTime: '19:30', endTime: '20:30', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: '', isDefault: true },

  { id: 'wed-1', courseCode: 'MN 392', courseName: 'Practical', day: 'Wednesday', startTime: '07:00', endTime: '08:00', venue: 'FL A2', lecturer: 'AB YALLEY', type: 'PRACTICAL', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Early morning practical.', isDefault: true },
  { id: 'wed-2', courseCode: 'REST', courseName: 'Morning Break', day: 'Wednesday', startTime: '08:00', endTime: '09:00', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: '', isDefault: true },
  { id: 'wed-3', courseCode: 'MN 374', courseName: 'Surface Mining Systems', day: 'Wednesday', startTime: '09:00', endTime: '10:00', venue: 'VLE', lecturer: 'AB YALEY', type: 'CLASS_VLE', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Online via VLE.', isDefault: true },
  { id: 'wed-4', courseCode: 'MN 378', courseName: 'AI Application in Mining', day: 'Wednesday', startTime: '10:00', endTime: '11:00', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Prep for Thursday MN378(P).', isDefault: true },
  { id: 'wed-5', courseCode: 'MN 392', courseName: 'Practical', day: 'Wednesday', startTime: '11:00', endTime: '12:00', venue: 'CCL1', lecturer: 'S AL-HASSAN', type: 'PRACTICAL', notificationEnabled: true, notificationMinsBefore: 10, notes: '', isDefault: true },
  { id: 'wed-6', courseCode: 'MN 380', courseName: 'Mine Drainage', day: 'Wednesday', startTime: '13:30', endTime: '14:30', venue: 'GR 1', lecturer: 'EA MANTE', type: 'PRACTICAL', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Practical session.', isDefault: true },
  { id: 'wed-7', courseCode: 'MN 352', courseName: 'Research Methods & Ethics', day: 'Wednesday', startTime: '14:30', endTime: '15:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Prep for 15:30 MN352 class.', isDefault: true },
  { id: 'wed-8', courseCode: 'MN 352', courseName: 'Research Methods & Ethics', day: 'Wednesday', startTime: '15:30', endTime: '17:30', venue: 'FL B2', lecturer: 'F KUNKYIN-SAADAARI', type: 'CLASS_PHYSICAL', notificationEnabled: true, notificationMinsBefore: 10, notes: '2 hour class. Dr Kunkyin-Saadaari.', isDefault: true },
  { id: 'wed-9', courseCode: 'MN 370', courseName: 'Computer Applications in Mining', day: 'Wednesday', startTime: '17:30', endTime: '18:30', venue: 'GF 4', lecturer: 'G ATVOR', type: 'PRACTICAL', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Practical session.', isDefault: true },
  { id: 'wed-10', courseCode: 'REST', courseName: 'Evening Break', day: 'Wednesday', startTime: '18:30', endTime: '19:30', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: '', isDefault: true },
  { id: 'wed-11', courseCode: 'MN 378', courseName: 'AI Application in Mining', day: 'Wednesday', startTime: '19:30', endTime: '20:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Light evening session.', isDefault: true },

  { id: 'thu-1', courseCode: 'REST', courseName: 'Morning Rest', day: 'Thursday', startTime: '07:00', endTime: '09:00', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: '', isDefault: true },
  { id: 'thu-2', courseCode: 'MN 378', courseName: 'AI Application in Mining', day: 'Thursday', startTime: '09:00', endTime: '10:00', venue: 'CCU', lecturer: 'BT AKUNOR', type: 'PRACTICAL', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Practical session.', isDefault: true },
  { id: 'thu-3', courseCode: 'MN 378', courseName: 'AI Application in Mining', day: 'Thursday', startTime: '10:00', endTime: '11:00', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: "Review today's practical.", isDefault: true },
  { id: 'thu-4', courseCode: 'MN 392', courseName: 'Practical', day: 'Thursday', startTime: '11:00', endTime: '12:00', venue: 'VLE', lecturer: 'F KUNKYIN-SAADAARI', type: 'CLASS_VLE', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Online via VLE.', isDefault: true },
  { id: 'thu-5', courseCode: 'MN 374', courseName: 'Surface Mining Systems', day: 'Thursday', startTime: '12:00', endTime: '13:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Priority course consolidation.', isDefault: true },
  { id: 'thu-6', courseCode: 'MN 360', courseName: 'Course', day: 'Thursday', startTime: '13:30', endTime: '14:30', venue: 'VLE', lecturer: 'EA MANTE', type: 'CLASS_VLE', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Online via VLE.', isDefault: true },
  { id: 'thu-7', courseCode: 'REST', courseName: 'Afternoon Break', day: 'Thursday', startTime: '14:30', endTime: '15:30', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: '', isDefault: true },
  { id: 'thu-8', courseCode: 'MN 170', courseName: 'Course', day: 'Thursday', startTime: '16:30', endTime: '17:30', venue: 'VLE', lecturer: 'G ATVOR', type: 'CLASS_VLE', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Online via VLE.', isDefault: true },
  { id: 'thu-9', courseCode: 'MN 352', courseName: 'Research Methods & Ethics', day: 'Thursday', startTime: '17:30', endTime: '18:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Evening study block.', isDefault: true },
  { id: 'thu-10', courseCode: 'MN 014', courseName: 'Course', day: 'Thursday', startTime: '18:30', endTime: '19:30', venue: 'VLE', lecturer: 'FC QUANSAH', type: 'CLASS_VLE', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Online via VLE.', isDefault: true },
  { id: 'thu-11', courseCode: 'REST', courseName: 'Evening Break', day: 'Thursday', startTime: '19:30', endTime: '20:30', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: '', isDefault: true },
  { id: 'thu-12', courseCode: 'MN 382', courseName: 'Mine Machinery', day: 'Thursday', startTime: '20:30', endTime: '21:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Final block of the day.', isDefault: true },

  { id: 'fri-1', courseCode: 'REST', courseName: 'Morning Rest', day: 'Friday', startTime: '07:00', endTime: '09:00', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: '', isDefault: true },
  { id: 'fri-2', courseCode: 'MN 378', courseName: 'AI Application in Mining', day: 'Friday', startTime: '09:00', endTime: '10:00', venue: 'VLE', lecturer: 'BT AKUNOR', type: 'CLASS_VLE', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Online via VLE.', isDefault: true },
  { id: 'fri-3', courseCode: 'REST', courseName: 'Mid-Morning Break', day: 'Friday', startTime: '10:00', endTime: '11:00', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: '', isDefault: true },
  { id: 'fri-4', courseCode: 'MN 276', courseName: 'Practical', day: 'Friday', startTime: '11:00', endTime: '12:00', venue: 'FL A3', lecturer: 'JB BAIDOE', type: 'PRACTICAL', notificationEnabled: true, notificationMinsBefore: 10, notes: 'Practical session.', isDefault: true },
  { id: 'fri-5', courseCode: 'MN 374', courseName: 'Surface Mining Systems', day: 'Friday', startTime: '12:00', endTime: '13:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Priority course deep study.', isDefault: true },
  { id: 'fri-6', courseCode: 'MN 372', courseName: 'Underground Mining Systems', day: 'Friday', startTime: '13:30', endTime: '15:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Priority course weekly review.', isDefault: true },
  { id: 'fri-7', courseCode: 'REST', courseName: 'Afternoon Break', day: 'Friday', startTime: '15:30', endTime: '16:30', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: '', isDefault: true },
  { id: 'fri-8', courseCode: 'MN 378', courseName: 'AI Application in Mining', day: 'Friday', startTime: '16:30', endTime: '18:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'Weekly AI review.', isDefault: true },
  { id: 'fri-9', courseCode: 'MN 382', courseName: 'Mine Machinery', day: 'Friday', startTime: '18:30', endTime: '19:30', venue: '', lecturer: '', type: 'STUDY', notificationEnabled: true, notificationMinsBefore: 5, notes: 'End of week catch-up.', isDefault: true },
  { id: 'fri-10', courseCode: 'REST', courseName: 'Free Time', day: 'Friday', startTime: '19:30', endTime: '20:30', venue: '', lecturer: '', type: 'REST', notificationEnabled: false, notificationMinsBefore: 10, notes: 'Rest and recharge.', isDefault: true },
];

/** Official MN 3C class times — shared by all students, managed by admin. */
export const OFFICIAL_CLASSES = DEFAULT_CLASSES.filter((c) =>
  OFFICIAL_TYPES.includes(c.type)
);
